// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crfpxdjefkxfciuktucm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyZnB4ZGplZmt4ZmNpdWt0dWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTk2NzUsImV4cCI6MjA1NTg3NTY3NX0.DNPvL6uH35JLslO9DW3OsM41Ckd8kSgykbWKSwJ51kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);